#!/bin/bash

# applywarp.sh applies the warp MAT file generated by mcflirt in Step 9 to each individual timepoint for each of the five echoes
# Called by ../9_echo_warp.sh, submitted as a cluster job; takes ~10 hours to run
# -> cannot be parallelized unfortunately
# (unless we divide and conquer further but that would hog up a lot of CPUs)

# JD - 8/29/24
# Adapted from commands outlined by Julie Grier, Chuck Lynch

# Script inputs from bsub call
id=$1
echo_val=$2

# Dependencies
module load fsl/6.0.3

# Pathways

RESOURCE=/project/oathes_analysis2/R61/Liston-Laboratory-MultiEchofMRI-Pipeline-master/MultiEchofMRI-Pipeline/res0urces
ACPC=/project/oathes_analysis2/R61/ME_acpc
ECHO=/project/oathes_analysis2/R61/ME_acpc/$id/echoes

# Apply transform defined by premat MAT file to each echo E with SBref2ACPC as warp and MNI as ref
images=($ECHO/echo${echo_val}/E_${echo_val}_*.nii.gz)
mats=($ACPC/$id/Rest_AVG_mcf.mat/MAT_*)

for ((i=0; i<${#images[@]}; i++)); do
	echo "${images["$i"]}" 
	echo "${mats["$i"]}"
	applywarp --interp=spline \
	--in="${images["$i"]}" \
	--premat="${mats["$i"]}" \
	--warp=$ACPC/$id/AvgSBref2acpc_EpiReg_warp.nii.gz \
	--out="${images["$i"]}" \
	--ref=$RESOURCE/MNI152_T1_2mm.nii.gz
done









